version: '3'
services:
  nginx:
    image: nginx:latest
    volumes:
      - ./nginx-prerender.conf:/etc/nginx/conf.d/default.conf
    ports:
      - 8080:80
    depends_on:
      - prerender

  prerender:
    build: .
    expose:
      - "3000"
    environment:
      PRERENDER_SERVICE_URL: http://prerender:3000
